### ISSUE TITLE
Support Git-LFS as an alternative to separate lookaside system

### ISSUE THREAD

**Issue by Conan-Kudo** [release-engineering/dist-git#13]
When Dist-Git was first conceived by Fedora Infrastructure years ago, there were no recommended mechanisms for dealing with binary data. Today, we have [Git-LFS](https://git-lfs.github.com/), which is natively supported by [GitLab](https://docs.gitlab.com/ce/workflow/lfs/manage_large_binaries_with_git_lfs.html) and GitHub.

For fresh deployments, it would make sense to leverage Git-LFS rather than use the older solutions, since Git-LFS is natively supported in `git` (well, as close to natively as you can get, really). Unless there's a compelling reason not to, I don't see why fresh Git setups wouldn't use it.

**Comment by SEJeff** [comment]
Bitbucket also [supports LFS](https://confluence.atlassian.com/bitbucket/git-large-file-storage-in-bitbucket-829078514.html)

**Comment by clime** [comment]
Note that this also depends on a command-line tool being used. The current packaging tools based on python-rpkg are all about the 'sources' file and global configuration options to keep track of the sources. We are likely to implement support for git-lfs into https://pagure.io/rpkg-client.

**Comment by praiskup** [comment]
I'm downvoting this idea.

If you store the binary blobs out from dist-git, you no longer need dist-git.  This is bad idea, dist-git + dist-git-client (rpkg) always was a tight couple..  to completely track the sources of packages (not to store the data elsewhere) for reproducibility, to be self-standing and independent on the outside world.  

Encouraging a third-party sources might make dist-git upstream less convenient for Fedora/RHEL reusability.

**Comment by praiskup** [comment]
In other words, dist-git is not bitbucket/github alternative.  Dist-git is git-lfs alternative to self-host binary blobs, oriented (mostly) on RPM world..

**Comment by clime** [comment]
> to completely track the sources of packages (not to store the data elsewhere) for reproducibility, to be self-standing and independent on the outside world.

This has nothing to do with the problem, however. You can be completeely independent and still use git-lfs.

**Comment by praiskup** [comment]
So, if you use the LFS extension, where the binary blobs are stored?

**Comment by Conan-Kudo** [comment]
@praiskup Wherever you configure the LFS server to store them. The LFS extension more or less operates the same way as the lookaside cache, and when you control the Git server, you also control where the LFS objects are stored.

**Comment by praiskup** [comment]
I got it then, thanks.  It means that you are not able to reference third-party binary blobs, right?

Isn't this actually request to "obsolete dist-git" by git-lfs?  I still fail to see how, when the LFS is alternative to dist-git, we will benefit from using LFS.

**Comment by Conan-Kudo** [comment]
@praiskup No, since the blobs are deeply tied to the git repository, they have to be directly linked.

**Comment by praiskup** [comment]
@Conan-Kudo what's the benefit in hooking git-lfs into dist-git, instead of replacing dist-git by git-lfs?

**Comment by Conan-Kudo** [comment]
@praiskup It would effectively be replacing the lookaside cache, but maintaining the `sources` file with the checksums means that you can change the where the blobs are stored later if you want.

**Comment by Conan-Kudo** [comment]
After further reflection and understanding of how this system works, this RFE makes no sense.
