### ISSUE TITLE
RFE: (optional) grokmirror support

### ISSUE THREAD

**Issue by nirik** [release-engineering/dist-git#14]
It would be nice if dist-git supported (optionally) grokmirror out of the box.

If grokmirror is installed. 
And the config enables it. 
We add a grokmirror hook to all repos to update a manifest file everytime they get a commit. 
Then we generate a initial manifest and place it at the top level. 

Then users (or infrastructure backups) could poll every 5minutes or something and only mirror the git content thats changed. 

https://github.com/mricon/grokmirror
it is already packaged in Fedora/EPEL.

**Comment by clime** [comment]
Implemented by https://github.com/release-engineering/dist-git/commit/eb0c75da81a7ac901018a56a223aeddaa23db19e.
