### ISSUE TITLE
regression: srpm import commits are not authored by git_author_name

### ISSUE THREAD

**Issue by praiskup** [release-engineering/dist-git#19]
I have imported sources like:
```
$ git log origin/epel/7  | grep Author:
Author:     CoprDistGit <copr-devel@lists.fedorahosted.org>
Author:     Red Hat Copr dist-git <rhcopr-distgit@redhat.com>
```

**Comment by praiskup** [comment]
My config is:
```
[dist-git]
git_author_name = 'Red Hat Copr dist-git'
git_author_email = rhcopr-distgit@redhat.com
```

**Comment by clime** [comment]
Hello, as you can see from git log output. There is first commit by `Red Hat Copr dist-git <rhcopr-distgit@redhat.com>`. The second commit is by `CoprDistGit <copr-devel@lists.fedorahosted.org>`, which has its own settings. The `git_author_name and `git_author_email` configuration of `dist-git` are useful for `setup_git_package` script only.

**Comment by praiskup** [comment]
right
