### ISSUE TITLE
Allow using a single local repository with more remote ones (i.e. Fedora, Copr, etc.)

### ISSUE THREAD

**Issue by sorki** [release-engineering/dist-git#2]
Ideally, it should be possible to set rpkg URL per branch and use single repository for managing packages for e.g. fedora and copr based on the branch one is currently using.

So if I'm using f20 branch rpkg build would pick correct configuration and rpkg build would end up in fedora's koji. When using e.g. copr_f20 rpkg build would use copr for building my package and so on.

This would make it much easier for maintainers as there's no need to remember correct rpkg alias which in principle is only configuration.

**Comment by sorki** [comment]
(Created these issues based on discussion of current state of dist-git so we won't forget on these possible improvements. I might be able to contribute to both #1 and #2 in a month or so.)

**Comment by bochecha** [comment]
I'd argue that the dist-git servers should remain separated: one for Fedora, one for Copr.

Then, pyrpkg/fedpkg could base itself on the git **remote** rather than the git **branch**, to know where to build what.

You can easily share stuff between various remotes with git, so there's no reason to merge everything server-side.

**Comment by sorki** [comment]
Yup. Remotes should indeed be separated. As for picking correct configuration for a branch we can either use git remote or store it as a metadata in branches - we need to figure out what's the best way to do it and what configuration needs to be stored for fedpkg/copr/...

**Comment by sorki** [comment]
Fedpkg configuration: https://git.fedorahosted.org/cgit/fedpkg.git/tree/src/fedpkg.conf

It overrides some functionality like update and retire. There's also some code that does configuration based on branches - https://git.fedorahosted.org/cgit/fedpkg.git/tree/src/fedpkg/__init__.py#n121

**Comment by asamalik** [comment]
So you want to have a single local Dist Git Repository and be able to push some branches to Fedora Dist Git and others to Copr Dist Git? I like the idea!

**Comment by bochecha** [comment]
@asamalik I'll note here that this is exactly what I was trying to do with nbpkg. (my pyrpkg-based tool from a previous job)

Locally, I had only one git repo per package, with a remote pointing to Fedora and a remote pointing to our internal dist-git.

It was super handy to flow changes to my packages in both directions.

I never finished it properly (only some commands got done to interact with both remotes), but ideally I could have just done "nbpkg build" and it would have figured out whether to send the build to Fedora or my own Koji.

You can imagine how it could be useful for RHEL packagers as well, working with a Fedora remote, for example.

**Comment by yac** [comment]
So [rdopkg]() provides client-side utilities for similar multi-remote setup and much more.

See [initial repository setup](https://www.rdoproject.org/packaging/rdo-packaging.html#_initial_repository_setup) and [an example](https://www.rdoproject.org/packaging/rdopkg/rdopkg-adv-new-version.7.html) of manipulating such dist-git.

Finally, I plan to rewrite `fedpkg` and provide common utilities and conventions such as dist-git manipulation into a new [pwnpkg framework](https://github.com/yac/pwnpkg) that should end all this `*pkg` pain.

**Comment by Conan-Kudo** [comment]
This would also be extremely helpful from the Mageia side, as we regularly merge work from Fedora and would also like to easily send improvements back from our side to Fedora.

We're in the middle of [figuring out our own transition to Dist-Git](https://bugs.mageia.org/show_bug.cgi?id=20351), too.

**Comment by clime** [comment]
>Ideally, it should be possible to set rpkg URL per branch and use single repository for managing packages for e.g. fedora and copr based on the branch one is currently using.

>So if I'm using f20 branch rpkg build would pick correct configuration and rpkg build would end up in fedora's koji. When using e.g. copr_f20 rpkg build would use copr for building my package and so on.

>This would make it much easier for maintainers as there's no need to remember correct rpkg alias which in principle is only configuration.

This is an old issue but I would like to note there is now --config option for fedpkg/rpkg clients so you can have multiple configs for different dist-git servers and switch between them. This feature would need to be implemented at client-side anyway. See https://pagure.io/rpkg-client or https://pagure.io/rpkg (the latter is more suitable for the feature but the former may provide the functionality as well).

**Comment by clime** [comment]
Please, if you wish for this functionality, open ticket against https://pagure.io/rpkg-client.
