### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by xsuchy** [release-engineering/dist-git#25]
When I try to build dist-git package it fails with:
```
LC_ALL=C rpkg srpm
Wrote: /tmp/rpkg/dist-git-4-93ku35xc/dist-git.spec
error: Bad source: /tmp/rpkg/dist-git-4-93ku35xc/dist-git-1.10.tar.gz: No such file or directory
Failed to execute command.
```
@clime do you have an idea why it is failing?

**Comment by clime** [comment]
Hello @xsuchy,

my guess is that you have auto-packing disabled in `/etc/rpkg.conf`. `auto_pack` should be True to build this project.

**Comment by xsuchy** [comment]
Indeed. I have:
```
# auto-packing is deprecated:
auto_pack = False
```
Obviously, I do not want to use something deprecated. The page `https://pagure.io/rpkg-util` does not mention what should be instead. Any hint @clime ?

**Comment by praiskup** [comment]
We can probably create `/rpkg.conf` in this git and override the defaults.

**Comment by clime** [comment]
Adding rpkg.conf is one option, another using spec templates but i would just add the rpkg.conf file for now.

**Comment by clime** [comment]
Fixed by https://github.com/release-engineering/dist-git/commit/27d2617f740753cc284b5e24f0de619cb1ec3e60

**Comment by xsuchy** [comment]
This is just temporary fix. As I stated `auto_pack` is deprecated. So we should use something else. So what it the "else"?

**Comment by clime** [comment]
The "else" is "spec templates".
