### ISSUE TITLE
packaging issues

### ISSUE THREAD

**Issue by praiskup** [release-engineering/dist-git#28]
dist-git-selinux depends on dis-git (but not needed)

installing dist-git-selinux results to:
```
  Running scriptlet: dist-git-selinux-1.12-3.el8.noarch                                                                                                                                                                                  1/1 
/usr/sbin/restorecon: SELinux: Could not get canonical path for /var/lib/dist-git/cache restorecon: No such file or directory.
/usr/sbin/restorecon: SELinux: Could not get canonical path for /var/lib/dist-git/cache/lookaside restorecon: No such file or directory.
/usr/sbin/restorecon: SELinux: Could not get canonical path for /var/lib/dist-git/cache/lookaside/pkgs restorecon: No such file or directory.
/usr/sbin/restorecon: SELinux: Could not get canonical path for /var/lib/dist-git/git restorecon: No such file or directory.
/usr/sbin/restorecon: SELinux: Could not get canonical path for /var/lib/dist-git/web restorecon: No such file or directory.

  Verifying        : dist-git-selinux-1.12-3.el8.noarch      
```

**Comment by clime** [comment]
Hello!

Honestly, I struggle to imagine a use-case to install dist-git-selinux without dist-git but I don't mind enabling it if you think it would be useful.

How did you manage to actually install dist-git-selinux (which currently requires dist-git) and at the same time not having the `/var/lib/dist-git` paths created? Was it achieved by experimentation? I want to make sure I am not missing something...

Thank you

**Comment by clime** [comment]
Can you, please, review the #28 patch? Thanks

**Comment by praiskup** [comment]
>  I struggle to imagine a use-case to install dist-git-selinux

That's for backups.  Without having dist-git-selinux, I do not consider safe to
expect that selinux context on files is correctly backed up.

**Comment by clime** [comment]
Okay, let me know if the patch looks good to you.

**Comment by praiskup** [comment]
I believe this is fixed now.
