### ISSUE TITLE
Outdated Vagrantfile

### ISSUE THREAD

**Issue by FrostyX** [release-engineering/dist-git#30]
I wanted to run my own local instance of dist-git for development purposes and discovered several issues with `Vagrantfile`:

- It uses F29 which is now EOL
- It uses Tito but AFAIK the newest dist-git versions were released via rpkg
- When I tried to do `vagrant up`, hoping that I would at least get an outdated Fedora with an old dist-git package, vagrant didn't provision the instance successfully.

This is an issue particularly because beaker-tests seem to be tied to vagrant, so at this moment, we are not able to launch the latest version of dist-git and verify that it works.

**Comment by clime** [comment]
I will fix this today. If you are going to add the fedora messaging support, please, discuss it with me so that we can both reach a solution we are satisfied with.

**Comment by FrostyX** [comment]
Awesome, thank you @clime!

> please, discuss it with me so that we can both reach a solution we are satisfied with.

No, no. I am going to hack on different things.

**Comment by clime** [comment]
I looked at it but I hit some strange problem with Vagrant in general. I will need to give this more time. Note that if you want to spawn just the fedora box from Vagrantfile, run only `vagrant up dist-git`...in case you want to hack on your own for the time being. I will try to get back to it asap.

**Comment by FrostyX** [comment]
@clime, do you have any ETA for those tests? It would be nice to make a new release.

I can try to help with them, but I am afraid I will not get to it any sooner than next week.

**Comment by clime** [comment]
I will try this week.

**Comment by clime** [comment]
should be ok now.
