### ISSUE TITLE
Document how to build RPM package from upstream

### ISSUE THREAD

**Issue by FrostyX** [release-engineering/dist-git#46]
There are both Tito and Rpkg files in the repository and it is not obvious whether both are supported or which one is preferred.

**Comment by clime** [comment]
It should be documented in the readme:

```
$ rpkg srpm && rpkg local
```

etc.

Is the procedure not working? (there seem to be some discrepancies with the following dnf command)

**Comment by FrostyX** [comment]
I am blind, sorry. It's there.
