### ISSUE TITLE
"rpkg srpm && rpkg local" failed on fedora

### ISSUE THREAD

**Issue by Cav4ever** [release-engineering/dist-git#47]
The system I am using is fedora28.
I am using the newest code.
[root@bogon dist-git]# git log -1
commit 772daf8882c9826d09c07529e016f53226de3d99 (HEAD -> master, origin/master, origin/HEAD)
Merge: 7f8dc8e c4ed46a
Author: Michal Novotný <clime@fedoraproject.org>
Date:   Tue Feb 16 03:15:22 2021 +0100

    Merge pull request #45 from xsuchy/fullpath

    specify full path

When I run "**rpkg srpm && rpkg local**", I got the following error merssage:
[root@bogon dist-git]# rpkg srpm && rpkg local
Wrote: /tmp/rpkg/dist-git-1-spg05b0g/dist-git.spec
Wrote: /tmp/rpkg/dist-git-1-spg05b0g/dist-git-1.16.tar.gz
auto-packing: This function is deprecated and will be removed in a future release.
Wrote: /tmp/rpkg/dist-git-1-spg05b0g/dist-git-1.16-1.fc28.src.rpm
Wrote: /tmp/rpkg/dist-git-2-mdxsk0np/dist-git.spec
**error: Bad source: /tmp/rpkg/dist-git-2-mdxsk0np/dist-git-1.16.tar.gz: No such file or directory**
rpmbuild --define '_sourcedir /tmp/rpkg/dist-git-2-mdxsk0np' --define '_specdir /tmp/rpkg/dist-git-2-mdxsk0np' --define '_builddir /tmp/rpkg/dist-git-2-mdxsk0np' --define '_buildrootdir /tmp/rpkg/dist-git-2-mdxsk0np' --define '_srcrpmdir /tmp/rpkg/dist-git-2-mdxsk0np' --define '_rpmdir /tmp/rpkg/dist-git-2-mdxsk0np' -ba /tmp/rpkg/dist-git-2-mdxsk0np/dist-git.spec | tee /tmp/rpkg/dist-git-2-mdxsk0np/.build-1.16-1.fc28.log

Do you have an idea why it is failing?

**Comment by clime** [comment]
Hey,

try: 

`mkdir -p /tmp/rpkg/dist-git-build && rpkg srpm --outdir /tmp/rpkg/dist-git-build && rpkg local --outdir /tmp/rpkg/dist-git-build`

**Comment by Cav4ever** [comment]
> Hey,
> 
> try:
> 
> `mkdir -p /tmp/rpkg/dist-git-build && rpkg srpm --outdir /tmp/rpkg/dist-git-build && rpkg local --outdir /tmp/rpkg/dist-git-build`

Thanks a lot， it works.

**Comment by praiskup** [comment]
Instruction changed in #49, thanks for the report!
