### ISSUE TITLE
Deployment examples urls cannot be accessed

### ISSUE THREAD

**Issue by Cav4ever** [release-engineering/dist-git#48]
The urls of Deployment examples in README.md cannot be accessed now.
Would you please update them?

**Comment by Cav4ever** [comment]
> The urls of Deployment examples in README.md cannot be accessed now.
> Would you please update them?

https://pagure.io/fedora-infra/ansible/blob/master/f/roles/distgit
should be
https://pagure.io/fedora-infra/ansible/blob/main/f/roles/distgit
And
https://pagure.io/fedora-infra/ansible/blob/master/f/roles/copr/dist_git
should be
https://pagure.io/fedora-infra/ansible/blob/main/f/roles/copr/dist_git

**Comment by clime** [comment]
Thanks, good catch. I opened a pull request with those changes: https://github.com/release-engineering/dist-git/pull/50
