### ISSUE TITLE
Should pkgs-git-repos-list be replaced with repositories

### ISSUE THREAD

**Issue by tkdchen** [release-engineering/dist-git#7]
Should this 

```
echo "project-list=/var/lib/dist-git/git/pkgs-git-repos-list" >> /etc/cgitrc
```

be replaced with ?

```
echo "project-list=/var/lib/dist-git/git/repositories" >> /etc/cgitrc
```

Because, after installing dist-git which is built on the top of master branch, I only see two directories `repositories` and `rpms` under `/var/lib/dist-git/git/`.

**Comment by clime** [comment]
No, I don't think so, `project-list` stores list of repositories that cgit scans for git repos (at path defined by scan-path). 

But in the current version, cgit has been dropped from the base package (it's very easy to plug it in again though).

**Comment by clime** [comment]
I will close this issue as the package has been changed greatly from the time of this post. Feel free to reopen in case of further questions.
